services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../docprocai_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_DOCPROCAI_SERVICE=docprocai_service
  app-docprocai:
    build:
      context: ./../docprocai_service
      dockerfile: Dockerfile
    restart: always
    container_name: docprocai_service
    ports:
      - "9900:9900"
      - "9901:9901"
    depends_on:
      - database
  dapr-docprocai:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "docprocai_service",
      "--app-port", "9901",
      "--dapr-http-port", "9900",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../docprocai_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-media
      - redis
    network_mode: "service:app-docprocai"
volumes:
  dbdata:
networks:
  default:
      name: dapr-network
      external: true